# Generated by Django 3.1.6 on 2021-02-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=250, unique=True)),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField(default=1.0)),
                ('company', models.CharField(max_length=250)),
            ],
        ),
    ]
